name: Go CI

on:
  push:
    branches: [ main ] # Run on pushes to the main branch
  pull_request:
    branches: [ main ] # Run on pull requests targeting the main branch

jobs:
  build-and-test:
    # Use the latest Ubuntu runner provided by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up the Go environment (adjust version if needed)
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Match the Go version in your go.mod if different

    # 3. Cache Go modules to speed up subsequent runs
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-v1
        restore-keys: |
          ${{ runner.os }}-go-

    # 4. Build the project (optional but good practice)
    - name: Build
      run: go build -v ./...

    # 5. Run unit tests (tests without the 'integration' tag)
    - name: Run Unit Tests
      run: go test -v ./...

    # 6. Run integration tests (requires Docker, which is available on GitHub runners)
    #    These will use the 'integration' tag to include integration_test.go
    - name: Run Integration Tests
      run: go test -tags integration -v ./... 