# .github/workflows/release.yml

name: Build, Test, and Release

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    tags:
      - 'v*.*.*'      # Trigger on standard tags like v1.0.0
      - 'v*.*.*-*'    # Trigger on pre-release tags like v1.0.0-beta.1

permissions:
  contents: write # Allow creating releases and uploading assets

jobs:
  build:
    name: Build & Test for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        # Add other GOOS/GOARCH combinations if needed, e.g., arm64
        # goos: [linux, windows, darwin, linux]
        # goarch: [amd64, amd64, amd64, arm64]
        # include:
        #   - goos: darwin
        #     goarch: arm64 # For Apple Silicon Macs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Specify your Go version, ideally match go.mod

      - name: Run unit tests
        run: go test -v ./...

      - name: Build sshx binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Set output name to sshx or sshx.exe
          OUTPUT_NAME="sshx"
          if [ "${GOOS}" == "windows" ]; then
            OUTPUT_NAME="${OUTPUT_NAME}.exe"
          fi
          echo "Building $OUTPUT_NAME..."
          go build -v -o "${OUTPUT_NAME}" .
          ls -l # Verify file exists

      - name: Upload artifact
        # Artifacts will be uploaded for branch pushes too,
        # useful for testing/debugging builds, but won't be released.
        uses: actions/upload-artifact@v4
        with:
          name: sshx-build-${{ matrix.goos }}-${{ matrix.goarch }} # Keep unique artifact name per build
          # Upload the plain sshx or sshx.exe file
          path: sshx*
          retention-days: 1 # Keep artifacts for 1 day

  release:
    # Add condition to only run this job for tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build # Run after all builds are finished
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # Download all artifacts into an 'artifacts' directory
          # The artifacts will be in subdirectories named after the upload name

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          # Use a simpler glob pattern to find all downloaded artifacts
          artifacts: artifacts/*/*
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: contains(github.ref, '-')

      - name: Output Release URL
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.html_url }}" 